# Generated by Django 4.0 on 2023-09-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_center', models.CharField(max_length=50)),
                ('crew_size', models.IntegerField(default=1)),
            ],
        ),
    ]
