# Generated by Django 4.0 on 2023-09-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='crew_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
