# Generated by Django 4.0 on 2023-09-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_crew_crew_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='crew_name',
            field=models.CharField(blank=True, default='new crew', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='crew_size',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='work_center',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
