# Generated by Django 4.0 on 2023-09-03 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acft', '0002_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='acft',
            name='crews_assigned',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='acft.crew'),
        ),
    ]
