# Generated by Django 4.0 on 2023-09-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acft', '0004_acft_acft_mx_status_alter_acft_crews_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='acft',
            name='acft_mission_status',
            field=models.CharField(blank=True, choices=[('INW', 'In-work'), ('INW-X', 'In-work, no addtional crews permitted'), ('AWM-1', 'Awaiting Maintenance Code 1'), ('AWM-2', 'Awaiting Maintenance Code 2'), ('AWM-3', 'Awaiting Maintenance Code 3'), ('AWP', 'Awaiting Parts'), ('RDY', 'Ready for Lines, No MX required')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acft',
            name='acft_mx_status',
            field=models.CharField(blank=True, choices=[('NMC', 'Not Mission Capable'), ('PMC', 'Partially Mission Capable'), ('FMC', 'Fully Mission Capable')], default=None, max_length=255, null=True),
        ),
    ]
