# Generated by Django 4.0 on 2023-09-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acft', '0006_alter_acft_crews_assigned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crew',
        ),
    ]
